//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalOrder
    {
        public MedicalOrder()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int UID { get; set; }
        public int Medical { get; set; }
        public string Count { get; set; }
    
        public virtual MedicalList MedicalList { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
