//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VitaFarmEntities : DbContext
    {
        public VitaFarmEntities()
            : base("name=VitaFarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ассортимент> Ассортимент { get; set; }
        public DbSet<Пользователи> Пользователи { get; set; }
        public DbSet<ПунктыВыдачи> ПунктыВыдачи { get; set; }
        public DbSet<Роли> Роли { get; set; }
        public DbSet<Состав> Состав { get; set; }
        public DbSet<Талоны> Талоны { get; set; }
    }
}
