//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int UID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int User { get; set; }
        public int ListMed { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<float> Perc { get; set; }
        public int OutPlace { get; set; }
    
        public virtual MedicalOrder MedicalOrder { get; set; }
        public virtual OutPlaces OutPlaces { get; set; }
        public virtual Users Users { get; set; }
    }
}
