//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int UID { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Phone { get; set; }
        public int Role { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
