//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ассортимент
    {
        public Ассортимент()
        {
            this.Состав = new HashSet<Состав>();
        }
    
        public int UID { get; set; }
        public byte[] Фотография { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public string Производитель { get; set; }
        public decimal Цена { get; set; }
        public string Измерение { get; set; }
        public string Количество { get; set; }
        public float Скидка { get; set; }
    
        public virtual ICollection<Состав> Состав { get; set; }
    }
}
