//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public Пользователи()
        {
            this.Талоны = new HashSet<Талоны>();
        }
    
        public int UID { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public int Роль { get; set; }
    
        public virtual Роли Роли { get; set; }
        public virtual ICollection<Талоны> Талоны { get; set; }
    }
}
