//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав
    {
        public Состав()
        {
            this.Талоны = new HashSet<Талоны>();
        }
    
        public int UID { get; set; }
        public int Медикомент { get; set; }
        public string Количество { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Ассортимент Ассортимент { get; set; }
        public virtual ICollection<Талоны> Талоны { get; set; }
    }
}
