//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaFarm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Талоны
    {
        public int UID { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public int Покупатель { get; set; }
        public int Состав { get; set; }
        public decimal Сумма { get; set; }
        public Nullable<float> Скидка { get; set; }
        public int Пункт_выдачи { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктыВыдачи ПунктыВыдачи { get; set; }
        public virtual Состав Состав1 { get; set; }
    }
}
